/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.UserList;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author deshna
 */
public class CreateUserPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateUserPanel
     */
    UserList ul;
    public CreateUserPanel(UserList ul) {
        initComponents();
        this.ul = ul;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enabledtxt = new javax.swing.JComboBox<>();
        passwordtxt = new javax.swing.JTextField();
        enabledlb = new javax.swing.JLabel();
        emaillb = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        neuidlb = new javax.swing.JLabel();
        firstnamelb = new javax.swing.JLabel();
        neuidtxt = new javax.swing.JTextField();
        lastnametxt = new javax.swing.JTextField();
        firstnametxt = new javax.swing.JTextField();
        usernamelb = new javax.swing.JLabel();
        lastnamelb = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        createbtn = new javax.swing.JButton();
        passwordlb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 102, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enabledtxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enabledtxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        add(enabledtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 339, 239, 36));
        add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 243, 239, 36));

        enabledlb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        enabledlb.setText("Enabled");
        add(enabledlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 347, 61, -1));

        emaillb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emaillb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emaillb.setText("Email ID");
        add(emaillb, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 298, -1, -1));
        add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 291, 239, 36));

        jLabel1.setFont(new java.awt.Font("Engravers MT", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, 780, -1));

        neuidlb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        neuidlb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        neuidlb.setText("NEUID:");
        add(neuidlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 64, 70, -1));

        firstnamelb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        firstnamelb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstnamelb.setText("First Name");
        add(firstnamelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 160, 99, -1));
        add(neuidtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 57, 239, 36));
        add(lastnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 201, 239, 36));
        add(firstnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 153, 239, 36));

        usernamelb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernamelb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernamelb.setText("User Name");
        add(usernamelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 112, 99, -1));

        lastnamelb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lastnamelb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastnamelb.setText("Last Name");
        add(lastnamelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 208, 88, -1));
        add(usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 105, 239, 36));

        createbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createbtn.setText("Create");
        createbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbtnActionPerformed(evt);
            }
        });
        add(createbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 106, 43));

        passwordlb.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordlb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordlb.setText("Password");
        add(passwordlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 250, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbtnActionPerformed
        boolean isEnabled = "Yes".equals(enabledtxt.getSelectedItem().toString());
        String passwordHashed = UserList.HashPassword(passwordtxt.getText());
        var a = ul.addNewUser();
        a.setneuid(neuidtxt.getText());
        a.setFirstName(firstnametxt.getText());
        a.setLastName(lastnametxt.getText());
        a.setUserName(usernametxt.getText());
        a.setPassword(passwordHashed);
        a.setEmailID(emailtxt.getText());
        a.setIsEnabled(isEnabled);
        a.setPreviousPass(new ArrayList<>());
        
        JOptionPane.showMessageDialog(this, "User Created Successfully");
    }//GEN-LAST:event_createbtnActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createbtn;
    private javax.swing.JLabel emaillb;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel enabledlb;
    private javax.swing.JComboBox<String> enabledtxt;
    private javax.swing.JLabel firstnamelb;
    private javax.swing.JTextField firstnametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastnamelb;
    private javax.swing.JTextField lastnametxt;
    private javax.swing.JLabel neuidlb;
    private javax.swing.JTextField neuidtxt;
    private javax.swing.JLabel passwordlb;
    private javax.swing.JTextField passwordtxt;
    private javax.swing.JLabel usernamelb;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
